# Generated by Django 5.2.16 on 2026-07-17 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('tenants', '0002_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencial', models.CharField(max_length=20)),
                ('clave_acceso', models.CharField(blank=True, max_length=49)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('razon_social_cliente', models.CharField(max_length=300)),
                ('identificacion_cliente', models.CharField(max_length=20)),
                ('direccion_cliente', models.TextField(blank=True)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('autorizada', 'Autorizada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('xml_generado', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='finanzas.pago')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
