# Generated by Django 5.2.16 on 2026-07-17 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/logos/')),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
                'verbose_name_plural': 'Configuración del Negocio',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_emisor', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=300)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300)),
                ('direccion_matriz', models.TextField()),
                ('codigo_establecimiento', models.CharField(default='001', max_length=3)),
                ('codigo_punto_emision', models.CharField(default='001', max_length=3)),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1)),
                ('certificado_p12', models.FileField(blank=True, null=True, upload_to='configuracion/sri/')),
                ('clave_certificado', models.CharField(blank=True, max_length=200)),
                ('secuencial_factura', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_sri', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuración SRI',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_whatsapp', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Número de WhatsApp',
                'verbose_name_plural': 'Números de WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20)),
                ('titular', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita_proxima', 'Recordatorio de cita próxima'), ('saldo_pendiente', 'Recordatorio de saldo pendiente'), ('regreso_tratamiento', 'Recordatorio de regreso de tratamiento')], max_length=50)),
                ('mensaje', models.TextField()),
                ('dias_anticipacion', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_mensaje', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje',
                'verbose_name_plural': 'Plantillas de Mensajes',
                'unique_together': {('tenant', 'tipo')},
            },
        ),
    ]
